runtime: nodejs20
handlers:
  - url: /static
    static_dir: dist/
  - url: /favicon.ico
    static_files: dist/favicon.ico
    upload: dist/favicon.ico
  - url: /
    static_files: dist/index.html
    upload: dist/index.html
