# Gunakan image Node.js versi 20 berbasis Alpine
FROM node:20-alpine

# Tentukan direktori kerja di dalam container
WORKDIR /app

# Salin file package.json dan package-lock.json terlebih dahulu untuk mengoptimalkan caching
COPY package.json package-lock.json ./

# Instal dependensi
RUN npm install

# Salin seluruh file aplikasi (termasuk file frontend dan konfigurasi)
COPY . .

# Build aplikasi untuk produksi
RUN npm run build

# Instal 'serve' untuk menyajikan file statis hasil build
RUN npm install -g serve

# Ekspos port 8080, karena Cloud Run dan App Engine biasanya menggunakan port ini
EXPOSE 8080

# Jalankan aplikasi menggunakan 'serve' untuk menyajikan file statis di port 8080
CMD ["serve", "-s", "dist", "-l", "8080"]
